import React from 'react';
import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Progress } from '../components/ui/Progress';
import { Button } from '../components/ui/Button';
import {
  CheckCircle2,
  Circle,
  Clock,
  Filter,
  Plus,
  ChevronRight,
  Gavel,
  Megaphone,
  Briefcase,
  Layers,
  Coins,
} from 'lucide-react';
import { mockRoadmap } from '../data/mock';
import type { RoadmapItem, RoadmapCategory } from '../types';
import { cn } from '../utils/cn';

type FilterValue = RoadmapCategory | 'all';

const CATEGORY_ICONS: Record<RoadmapCategory, React.ElementType> = {
  legal: Gavel,
  marketing: Megaphone,
  operations: Briefcase,
  product: Layers,
  financial: Coins,
};

const CATEGORIES = Object.keys(CATEGORY_ICONS) as RoadmapCategory[];

export default function RoadmapPage() {
  const [tasks, setTasks] = useState<RoadmapItem[]>(mockRoadmap);
  const [filter, setFilter] = useState<FilterValue>('all');

  const filteredTasks = filter === 'all' ? tasks : tasks.filter((t) => t.category === filter);
  const completedCount = tasks.filter((t) => t.status === 'completed').length;
  const progress = tasks.length > 0 ? Math.round((completedCount / tasks.length) * 100) : 0;

  const toggleTask = (id: string) => {
    setTasks((prev) =>
      prev.map((t) =>
        t.id === id
          ? { ...t, status: t.status === 'completed' ? 'in-progress' : 'completed' }
          : t
      )
    );
  };

  return (
    <div className="space-y-8 pb-20">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-1">
          <h1 className="text-4xl font-black tracking-tight text-white uppercase italic">
            Growth Blueprint.
          </h1>
          <p className="text-slate-400 font-medium">
            Strategic execution path generated by BizLaunch Neural Engine.
          </p>
        </div>
        <Button className="h-12 px-6 gap-2 shrink-0">
          <Plus size={18} aria-hidden="true" />
          New Milestone
        </Button>
      </header>

      <div className="grid lg:grid-cols-4 gap-8">
        {/* Main list — 3 cols */}
        <div className="lg:col-span-3 space-y-6">
          {/* Progress card */}
          <Card className="bg-indigo-600/5 border-white/5 relative overflow-hidden p-8">
            <div className="flex items-center justify-between mb-4">
              <div className="space-y-1">
                <h3 className="text-xl font-bold text-white">Project Velocity</h3>
                <p className="text-xs text-slate-400 font-bold uppercase tracking-widest">
                  {completedCount} of {tasks.length} milestones reached
                </p>
              </div>
              <span className="text-4xl font-black text-white" aria-hidden="true">
                {progress}%
              </span>
            </div>
            <Progress
              value={progress}
              label={`Overall project progress: ${progress}%`}
              className="h-3"
            />
          </Card>

          {/* Category filters */}
          <div
            className="flex flex-wrap gap-2"
            role="group"
            aria-label="Filter milestones by category"
          >
            <button
              type="button"
              onClick={() => setFilter('all')}
              className={cn(
                'px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest transition-all',
                filter === 'all'
                  ? 'bg-white text-slate-900'
                  : 'bg-white/5 text-slate-400 hover:bg-white/10 hover:text-white'
              )}
              aria-pressed={filter === 'all'}
            >
              All Stages
            </button>

            {CATEGORIES.map((cat) => (
              <button
                key={cat}
                type="button"
                onClick={() => setFilter(cat)}
                className={cn(
                  'px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest transition-all',
                  filter === cat
                    ? 'bg-indigo-600 text-white'
                    : 'bg-white/5 text-slate-400 hover:bg-white/10 hover:text-white'
                )}
                aria-pressed={filter === cat}
              >
                {cat}
              </button>
            ))}
          </div>

          {/* Task List */}
          <div className="space-y-3" role="list" aria-label="Roadmap milestones">
            <AnimatePresence mode="popLayout">
              {filteredTasks.length === 0 && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="text-center py-16 text-slate-500"
                >
                  <Filter size={32} className="mx-auto mb-3 opacity-30" />
                  <p className="text-sm font-medium">No milestones in this category yet.</p>
                </motion.div>
              )}

              {filteredTasks.map((task) => {
                const Icon = CATEGORY_ICONS[task.category];
                return (
                  <motion.div
                    key={task.id}
                    layout
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.97 }}
                    role="listitem"
                  >
                    <Card
                      className={cn(
                        'group transition-all duration-300 p-0 overflow-hidden',
                        task.status === 'completed'
                          ? 'opacity-60 border-transparent bg-white/[0.01]'
                          : 'hover:border-indigo-500/30'
                      )}
                    >
                      <div className="flex items-stretch">
                        {/* Toggle button */}
                        <button
                          type="button"
                          onClick={() => toggleTask(task.id)}
                          aria-label={
                            task.status === 'completed'
                              ? `Mark "${task.title}" as in-progress`
                              : `Mark "${task.title}" as completed`
                          }
                          className={cn(
                            'w-16 flex items-center justify-center border-r border-white/5 transition-colors shrink-0',
                            task.status === 'completed'
                              ? 'bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20'
                              : 'text-slate-600 hover:bg-white/5 hover:text-white'
                          )}
                        >
                          {task.status === 'completed' ? (
                            <CheckCircle2 size={24} />
                          ) : (
                            <Circle size={24} />
                          )}
                        </button>

                        {/* Content */}
                        <div className="flex-1 p-5 flex flex-col md:flex-row md:items-center justify-between gap-4 min-w-0">
                          <div className="space-y-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <Icon size={13} className="text-indigo-400 shrink-0" aria-hidden="true" />
                              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">
                                {task.category}
                              </span>
                            </div>
                            <h4
                              className={cn(
                                'font-bold text-lg text-white group-hover:text-indigo-300 transition-colors truncate',
                                task.status === 'completed' && 'line-through text-slate-500'
                              )}
                            >
                              {task.title}
                            </h4>
                            <p className="text-sm text-slate-500 line-clamp-2">
                              {task.description}
                            </p>
                          </div>

                          <div className="flex items-center gap-3 shrink-0">
                            <Badge
                              variant={
                                task.priority === 'high'
                                  ? 'danger'
                                  : task.priority === 'medium'
                                  ? 'warning'
                                  : 'info'
                              }
                            >
                              {task.priority}
                            </Badge>
                            <button
                              type="button"
                              aria-label={`View details for ${task.title}`}
                              className="p-2 rounded-lg bg-white/5 text-slate-500 hover:text-white transition-colors"
                            >
                              <ChevronRight size={18} />
                            </button>
                          </div>
                        </div>
                      </div>
                    </Card>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          </div>
        </div>

        {/* Sidebar — 1 col */}
        <div className="space-y-6">
          <Card className="bg-white/5 border-dashed border-white/10 p-6 rounded-[32px]">
            <div className="flex items-center gap-3 mb-6">
              <div className="bg-amber-500/20 p-2 rounded-xl text-amber-400">
                <Clock size={18} aria-hidden="true" />
              </div>
              <h4 className="font-bold text-white uppercase tracking-wider text-xs">
                Upcoming Deadline
              </h4>
            </div>
            <p className="text-sm text-slate-300 leading-relaxed font-medium mb-4">
              Berlin Pilot registration expires in{' '}
              <strong className="text-amber-400">3 days</strong>. Ensure all legal artifacts are
              uploaded.
            </p>
            <Button variant="outline" size="sm" className="w-full">
              Review Requirements
            </Button>
          </Card>

          <div className="p-4">
            <h5 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 mb-4 px-2">
              Path Critical Factors
            </h5>
            <div className="space-y-3">
              {[
                { label: 'Regulatory Risk', score: 'Low', color: 'text-emerald-400' },
                { label: 'Market Demand', score: 'Aggressive', color: 'text-indigo-400' },
                { label: 'Capital Burn', score: 'Optimized', color: 'text-white' },
              ].map((item) => (
                <div
                  key={item.label}
                  className="flex items-center justify-between p-3 rounded-2xl bg-white/[0.02] border border-white/5"
                >
                  <span className="text-xs font-bold text-slate-400">{item.label}</span>
                  <span className={cn('text-xs font-black uppercase tracking-widest', item.color)}>
                    {item.score}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}