import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Card, CardHeader, CardTitle, CardContent } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Progress } from '../components/ui/Progress';
import { Button } from '../components/ui/Button';
import { 
  CheckCircle2, 
  Circle, 
  Clock, 
  AlertCircle, 
  Filter, 
  Plus, 
  ChevronRight,
  Gavel,
  Megaphone,
  Briefcase,
  Layers,
  Coins
} from 'lucide-react';
import { mockRoadmap } from '../data/mock';
import { RoadmapItem } from '../types';
import { cn } from '../utils/cn';

const categoryIcons = {
  legal: Gavel,
  marketing: Megaphone,
  operations: Briefcase,
  product: Layers,
  financial: Coins,
};

export default function RoadmapPage() {
  const [tasks, setTasks] = useState<RoadmapItem[]>(mockRoadmap);
  const [filter, setFilter] = useState<RoadmapItem['category'] | 'all'>('all');

  const filteredTasks = filter === 'all' ? tasks : tasks.filter(t => t.category === filter);
  
  const completedCount = tasks.filter(t => t.status === 'completed').length;
  const progress = Math.round((completedCount / tasks.length) * 100);

  const toggleTask = (id: string) => {
    setTasks(prev => prev.map(t => {
      if (t.id === id) {
        return { ...t, status: t.status === 'completed' ? 'in-progress' : 'completed' };
      }
      return t;
    }));
  };

  return (
    <div className="space-y-8 pb-20">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-1">
          <h1 className="text-4xl font-black tracking-tight text-white uppercase italic">Growth Blueprint.</h1>
          <p className="text-slate-400 font-medium">Strategic execution path generated by BizLaunch Neural Engine.</p>
        </div>
        <Button className="h-12 px-6 gap-2">
          <Plus size={18} />
          New Milestone
        </Button>
      </header>

      <div className="grid lg:grid-cols-4 gap-8">
        <div className="lg:col-span-3 space-y-6">
          {/* Progress Overview */}
          <Card className="bg-indigo-600/5 border-white/5 relative overflow-hidden p-8">
             <div className="flex items-center justify-between mb-4">
                <div className="space-y-1">
                    <h3 className="text-xl font-bold text-white">Project Velocity</h3>
                    <p className="text-xs text-slate-400 font-bold uppercase tracking-widest">{completedCount} of {tasks.length} Milestones Reached</p>
                </div>
                <span className="text-4xl font-black text-white">{progress}%</span>
             </div>
             <Progress value={progress} className="h-3" />
          </Card>

          {/* Filters */}
          <div className="flex flex-wrap gap-2">
            <button 
              onClick={() => setFilter('all')}
              className={cn(
                "px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest transition-all",
                filter === 'all' ? "bg-white text-black" : "bg-white/5 text-slate-400 hover:bg-white/10"
              )}
            >All Stages</button>
            {Object.keys(categoryIcons).map(cat => (
              <button 
                key={cat}
                onClick={() => setFilter(cat as any)}
                className={cn(
                  "px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-widest transition-all",
                  filter === cat ? "bg-indigo-600 text-white" : "bg-white/5 text-slate-400 hover:bg-white/10"
                )}
              >
                {cat}
              </button>
            ))}
          </div>

          {/* Task List */}
          <div className="space-y-4">
             <AnimatePresence mode="popLayout">
               {filteredTasks.map((task) => {
                 const Icon = categoryIcons[task.category];
                 return (
                   <motion.div
                     key={task.id}
                     layout
                     initial={{ opacity: 0, y: 10 }}
                     animate={{ opacity: 1, y: 0 }}
                     exit={{ opacity: 0, scale: 0.95 }}
                   >
                     <Card className={cn(
                       "group transition-all duration-300 p-0 overflow-hidden",
                       task.status === 'completed' ? "opacity-60 border-transparent bg-white/[0.01]" : "hover:border-indigo-500/30"
                     )}>
                        <div className="flex items-stretch">
                           <button 
                             onClick={() => toggleTask(task.id)}
                             className={cn(
                               "w-16 flex items-center justify-center border-r border-white/5 transition-colors",
                               task.status === 'completed' ? "bg-emerald-500/10 text-emerald-400" : "hover:bg-white/5 text-slate-600 hover:text-white"
                             )}
                           >
                             {task.status === 'completed' ? <CheckCircle2 size={24} /> : <Circle size={24} />}
                           </button>
                           
                           <div className="flex-1 p-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
                              <div className="space-y-1">
                                 <div className="flex items-center gap-2 mb-1">
                                    <Icon size={14} className="text-indigo-400" />
                                    <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">{task.category}</span>
                                 </div>
                                 <h4 className={cn(
                                   "font-bold text-lg text-white group-hover:text-indigo-300 transition-colors",
                                   task.status === 'completed' && "line-through text-slate-500"
                                 )}>
                                   {task.title}
                                 </h4>
                                 <p className="text-sm text-slate-500 max-w-xl">{task.description}</p>
                              </div>
                              
                              <div className="flex items-center gap-3 shrink-0">
                                 <Badge variant={task.priority === 'high' ? 'danger' : task.priority === 'medium' ? 'warning' : 'info'}>
                                    {task.priority}
                                 </Badge>
                                 <button className="p-2 rounded-lg bg-white/5 text-slate-500 hover:text-white transition-colors">
                                    <ChevronRight size={18} />
                                 </button>
                              </div>
                           </div>
                        </div>
                     </Card>
                   </motion.div>
                 );
               })}
             </AnimatePresence>
          </div>
        </div>

        {/* Sidebar Insights */}
        <div className="space-y-6">
           <Card className="bg-white/5 border-dashed border-white/10 p-6 rounded-[32px]">
              <div className="flex items-center gap-3 mb-6">
                 <div className="bg-amber-500/20 p-2 rounded-xl text-amber-400">
                    <Clock size={18} />
                 </div>
                 <h4 className="font-bold text-white uppercase tracking-wider text-xs">Upcoming Deadline</h4>
              </div>
              <div className="space-y-4">
                 <p className="text-sm text-slate-300 leading-relaxed font-medium">
                    Berlin Pilot registration expires in <span className="text-amber-400">3 days</span>. Ensure all legal artifacts are uploaded.
                 </p>
                 <Button variant="outline" size="sm" className="w-full text-xs py-5">Review Requirements</Button>
              </div>
           </Card>

           <div className="p-6">
              <h5 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-500 mb-4 px-2">Path Critical Factors</h5>
              <div className="space-y-4">
                 {[
                    { label: 'Regulatory Risk', score: 'Low', color: 'text-emerald-400' },
                    { label: 'Market Demand', score: 'Aggressive', color: 'text-indigo-400' },
                    { label: 'Capital Burn', score: 'Optimized', color: 'text-white' },
                 ].map(item => (
                    <div key={item.label} className="flex items-center justify-between p-3 rounded-2xl bg-white/[0.02] border border-white/5">
                        <span className="text-xs font-bold text-slate-400">{item.label}</span>
                        <span className={cn("text-xs font-black uppercase tracking-widest", item.color)}>{item.score}</span>
                    </div>
                 ))}
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}
